# Generated by Django 4.2.27 on 2026-02-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_api_key',
            field=models.CharField(blank=True, help_text='OpenAI API key for AI-generated assignments', max_length=255),
        ),
    ]
