# Generated by Django 4.2.27 on 2026-02-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('enrollment', 'New Enrollment'), ('material', 'New Material'), ('feedback', 'New Feedback'), ('deadline', 'Assignment Deadline'), ('general', 'General')], max_length=20),
        ),
    ]
