# Generated by Django 4.2.27 on 2026-02-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='whiteboard_data',
            field=models.TextField(default='[]'),
        ),
    ]
